language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  include:
    - php: 5.6
      env:
        - ENVIRONMENT="coverage"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-stable --prefer-lowest --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$ENVIRONMENT" == 'coverage' ]; then php vendor/bin/ocula code-coverage:upload --format=php-clover coverage.clover --verbose; fi
  - ls -la
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
